version: 1
formatters:
  default:
    format: "[%(asctime)s] %(levelname)s > %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
  file:
    class: logging.handlers.RotatingFileHandler
    filename: "./logs/cosmostic-website.log"
    maxBytes: 52428800  # 50 MB
    backupCount: 5
    formatter: default
root:
  level: INFO
  handlers: [console, file]